CREATE TABLE `users` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`full_name` VARCHAR(50) NOT NULL,
	`email` VARCHAR(150) NOT NULL,
	`password` VARCHAR(255) NOT NULL,
	`date_created` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	UNIQUE KEY `email` (`email`) USING BTREE,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB;
